### ISSUE TITLE
 Request for Detailed README.md for API Integration

### ISSUE THREAD

**Issue by Venkateshvenki404224** [omkardarves/swagger#3]
It would be greatly appreciated if you could provide a more detailed README.md file. After configuring the Swagger settings, I am stuck and unsure about the next steps to take for the API integration. A comprehensive guide with step-by-step instructions would be extremely helpful in moving forward.

**Comment by omkardarves** [comment]
sure, allow me some time. I will put readme.md file

**Comment by Venkateshvenki404224** [comment]
Thanks, @omkardarves! If you could assist me with setting up the Swagger configuration, I would be more than happy to contribute by drafting a detailed README.md file. Your help would enable me to better understand the steps involved, and in return, I can document the process thoroughly for others. Let me know if this works for you.

**Comment by omkardarves** [comment]
hey @Venkateshvenki404224 I have updated the README.md, but yes we can talk if you would like some guidance.

I have posted a project structure and API endpoints as well. Please don't hesitate to let me know if you find any trouble.
