### ISSUE TITLE
hello, After installing via bench get-app https://github.com/omkardarves/swagger, within the swagger settings, select the Frappe module -> generate swagger json. How can the generated swagger.html be accessed via what link?

### ISSUE THREAD

**Issue by dgo2dance** [omkardarves/swagger#7]
hello,  After installing via bench get-app https://github.com/omkardarves/swagger, within the swagger settings, select the Frappe module -> generate swagger json. How can the generated swagger.html be accessed via what link?

![image](https://github.com/user-attachments/assets/8c761a70-ad63-48ee-a64d-f40db652e53f)

**Comment by omkardarves** [comment]
@dgo2dance go to {base_url}/swagger

Example -
yourdomain.com/swagger
localhost:8000/swagger
